### ISSUE TITLE
requested image platform 

### ISSUE THREAD

**Issue by yosun** [replicate/cog#1036]
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].`

Can cog be used to run dreambooth on a Mac, for example?

**Comment by jelling** [comment]
I had the same issue and went hunting in the Replicate Discord and found this from the Replicate CTO:

<img width="479" alt="image" src="https://github.com/replicate/cog/assets/1887486/5620010a-a861-44ab-bed4-409c37fd6ef9">

Cog Team, please consider updating the `Readme.MD` to mention this. 

Or perhaps just drop the claim of Mac support altogether. I appreciate that Cog and build on the Mac but not being able to run `predict` means the Mac really isn't suited for developing with Cog as every change would require a Docker rebuild and deploy to test.

**Comment by baticodes** [comment]
I have the same issue here.

**Comment by mattt** [comment]
Hi @yosun. The warning you're seeing about `linux/amd64` is fixed by https://github.com/replicate/cog/pull/1114. The error concerning GPU availability was fixed by #1069. Please try updating to the latest version of Cog ([v0.8.0-beta6](https://github.com/replicate/cog/releases/tag/v0.8.0-beta6)) and let me know if you're still seeing this.
