### ISSUE TITLE
Cog doesn't know if CUDA 11.7 is compatible with PyTorch 1.13.1. This might cause CUDA problems.

### ISSUE THREAD

**Issue by qingfengfenga** [replicate/cog#1043]
```
$ cog predict -i prompt="Simply put, the theory of relativity states that"
⚠ Cog doesn't know if CUDA 11.7 is compatible with PyTorch 1.13.1. This might cause CUDA problems.
Building Docker image from environment in cog.yaml...
```

**Comment by mattt** [comment]
This should be fixed by https://github.com/replicate/cog/pull/1057 (specifically, [this added mapping](https://github.com/replicate/cog/pull/1057/files#diff-23698939ce6aa6ca3cd61b49f1f5b519c87bc5719e331e0368cf22929069e325R108-R123)).

Please update to [Cog v0.8.0-beta2](https://github.com/replicate/cog/releases/tag/v0.8.0-beta2) and try again.
