### ISSUE TITLE
Communicate file permission errors when copying weights into separate layer

### ISSUE THREAD

**Issue by mattt** [replicate/cog#1184]
Some users have reported that running `cog build --separate-weights` sometimes creates images with some weights files missing. After investigation by @hongchaodeng, it looks like this is caused by a permission issue.

```
$ cog debug --separate-weights > /tmp/Dockerfile
$ docker build -t cog-example -f /tmp/Dockerfile
error checking context: no permission to read from [...]
```

Apparently, this error message isn't being surfaced by Cog. We should make sure these errors are communicated to the user, and do whatever we can to prevent them from happening.

**Comment by hongchaodeng** [comment]
Let me investigate it further

**Comment by hongchaodeng** [comment]
I have some findings to share:

## 1. Setting the right file permission will make it work

I just tried that after setting the correct file permission the files are good:

```bash
# adding permissions for others to read
$ sudo chmod 664 models/hub/checkpoints/955717e8-8726e21a.th

$ cog build --separate-weights --debug

# verify the file size is right
$ docker run --platform linux/amd64 --rm -it cog-musicgen-weights ls -l /src/models/hub/checkpoints/955717e8-8726e21a.th
-rw-rw-r--    1 root     root      84141911 Jun 21 15:47 /src/models/hub/checkpoints/955717e8-8726e21a.th
```

This time the file size is `84141911` which is exactly the same as original source.

> I set it back to 400 (`-rw------- 1 root root`) for the rest.=

## 2. `docker buildx build` created empty file but `docker build` failed immediately

Another weird thing is that `docker build` returns error, but `docker buildx build` doesn't:
```
$ docker build -t hongchao-test -f .tmp/Dockerfile .
error checking context: no permission to read from '/home/andreas/cog-musicgen/models/hub/checkpoints/955717e8-8726e21a.th'
$ echo $?
1

$ docker buildx build --file .tmp/Dockerfile --cache-to type=inline --tag cog-musicgen-weights --progress auto .
...
 => CACHED [2/2] COPY models/hub/checkpoints /src/models/hub/checkpoints                                                                                                                     0.0s
...
$ echo $?
0
```

Since we are using `docker buildx build` in cog, it returned no error and 'succeeded'.

## 3. Both `docker build` and `docker buildx build` seems to create empty file in the latest version

The docker version  was  `20.10.21` that I tried `docker build` and failed. After upgrading it to the latest `24.0.4`, `docker build` didn't fail but created empty file instead.

## My thoughts

I think a more reasonable solution would be to check all files permissions before building the images? Just make sure that the $current_user owns everything and provides chmod + chown instructions to help users achieve that?

@mattt What do you think?

**Comment by hongchaodeng** [comment]
Found the buildx issue for the same problem: https://github.com/docker/buildx/issues/1802

> Buildx runs as an unprivileged user program, so, yes the inability to read a file not readable by the user is expected.
> I would expect an error though ...
