### ISSUE TITLE
checksum mismatch for 0.8.6 release

### ISSUE THREAD

**Issue by chenrui333** [replicate/cog#1449]
👋 it looks like 0.8.6 release got re-created, raise this issue to confirm it. Thanks! 

relates to https://github.com/Homebrew/homebrew-core/pull/158001

**Comment by stefanb** [comment]
cc @mattt

**Comment by mattt** [comment]
Thanks for flagging this, @chenrui333 @stefanb.

It looks like the artifacts for the release were updated 4 days ago. Looking at past repo activity, this lines up with https://github.com/replicate/cog/pull/1467. 

@zeke Do I have that right?

**Comment by zeke** [comment]
Yep that was me. Sorry about the trouble. I did indeed re-upload those files because we had a string of releases where the asset names were incorrect/inconsistent. It was compounded by a [GitHub bug where assets can't be renamed if they have a file extension](https://www.loom.com/share/c2afb266eebf41b0b10be552d29aa1b9).

Do we need to take some action to reconcile those homebrew CI failures?

**Comment by chenrui333** [comment]
no worries at all, thanks for getting the fix PR merged. 💯
