### ISSUE TITLE
Is there a way to configure X server with cog? 

### ISSUE THREAD

**Issue by RafayelSusanyan** [replicate/cog#1480]
Is there a way to configure X server with cog? I need an X server to do off-screen rendering.

**Comment by mattt** [comment]
Hi @RafayelSusanyan. Sorry for not responding sooner.

Unfortunately, I don't have any specific recommendations for using X with Cog / Docker. This project is primarily focused on AI / ML applications, so that's not a use case that we're optimizing for.

Feel free to try asking around on [Discord](https://discord.com/invite/replicate). Our community is building lots of interesting things, and there's a good chance someone there could point you in the right direction.
