### ISSUE TITLE
How to create a queuing mechanism in cog using "celery" and "redis" for video processing?

### ISSUE THREAD

**Issue by anilpatelia** [replicate/cog#1666]
Please Guide me on how to create a queuing mechanism in "cog" using "celery" and "redis" for "video processing".

My requirement is I send a s3 url of video to the service and the code performs operations on the video and send response. 
The video processing takes a lot of time so, I am planning to put the video processing task in celery and send the id of the processing task. And after some time retrieve the result of the video processing using id.

**Comment by technillogue** [comment]
Replicate handles queueing for you. create a model with a predict function that just takes the s3 url and performs the operations. when you send a request to Replicate, it is queued in our redis with an id that can be used to retrieve the result.

if you're using cog outside of Replicate, I recommend designing a service that handles queuing and talks to the cog API, rather than implementing this inside the model code.
