### ISSUE TITLE
Avoid pushing large files on `cog push`

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#308]
Since code and weights are stored in the same Docker layer, making small changes can result in really long push times when model weights are in the hundreds of megabytes or gigabytes.

One potential solution could be a `build.model_files` option in cog.yaml, that saves those files in a separate layer before the code is added.

**Comment by andreasjansson** [comment]
Build times are also affected by large weights files. Any change in the code or dependencies requires all files in the working directory (including giant ones) to be re-added to the image.

Perhaps we should automatically add any files >1GB to the image before installing system dependencies and Python packages? That should make both builds and pushes faster since the layer containing the large weights file will be cached both locally and remotely.

**Comment by zeke** [comment]
Semi-related: https://github.com/replicate/cog/issues/209

**Comment by afiaka87** [comment]
> 

I think specifying the model files in the configuration works well and could maybe even allow for some other functionality such as a "fork" of a project that only changes its `build.model_files` but uses the same Predictor.

I also agree that a simple fix in the meantime would be to just detect the bigger files and add those automatically. Could also do lookup via suffix (e.g. `.pt`,`.plk`, `.pth`) or check the date modified attribute on the file.

**Comment by JosephCatrambone** [comment]
I like the idea of having a pre/post build stage for model copying (or just detecting ckpt/etc, like above).  Specifying `build.model_files` also seems fairly ergonomic and friendly for new people.

In terms of implementation, Docker itself doesn't deal very well with symlinks, otherwise we could just make and break symlinks when we needed to build the images.  (I tried to do `ln -s ~/.cache/huggingface ./models`, but it seems to be ignored.)  

Thoughts on configuration vs convention?  Picking a directory name like 'models' and using some of the built in Dockerfile functionality, like `COPY [^models]/*` seems like a low-effort solution, but also might break in the cases where people have their own implementations with a 'models' directory.

**Comment by bfirsh** [comment]
A potential quick fix discussed with @anotherjesse IRL last week: when generating the Dockerfile, find all the files larger than, say, 100MB and add those in a layer before `COPY . /src`.

That'll mean the last layer is small and will be the only thing that changes if you change source code.

**Comment by asadm** [comment]
Forgive for bumping this but is there a plan for this?

I assume this will also reduce some burden on replicate infra too.

**Comment by kirillrogovoy** [comment]
Similar case here, and so a similar problem.

I sometimes use Replicate to build quick ideas, because I don't have access to local GPU that can run the kind of stuff I'm building.

But it's annoying to have to wait for like 10 minutes on each code change while I cannot really test those changes locally.

Some `build.model_files` thing would have worked for me.

**Comment by amamir14** [comment]
is there some kind of size limit imposed by replicate on the size of the model image being pushed to the registry?
