### ISSUE TITLE
Make it clear that 'cog' is the specific cog mentioned in the README.md not any other

### ISSUE THREAD

**Issue by quarterturn** [replicate/cog#375]
There's a few different 'cogs' out there, it might be helpful to state they need to install the one specified in the readme.

**Comment by zeke** [comment]
Hi @quarterturn 👋🏼 

Thanks for your input. Can you help me understand where specifically this clarification is needed?

**Comment by zeke** [comment]
I think it's clear in the README that this project is called Cog, and that references to "cog" within this project would be about this project.

Since this issue was opened, we've also updated the README in this repo to include a table of contents to make it more clear what's covered, including installation:

![Screen Shot 2022-03-14 at 1 33 05 PM](https://user-images.githubusercontent.com/2289/158256580-0b5d4471-f7ea-456a-9756-d0e5056ebb1f.png)

Hopefully that helps. I'm going to close this, but feel free to weigh in if I'm missing something.
