### ISSUE TITLE
AMQP queue architecture

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#439]
The existing Redis streams-based queue worker uses one request queue per Cog model, and one ephemeral response queue per request.

RabbitMQ's documentation explains this pattern in [Tutorial 6](https://www.rabbitmq.com/tutorials/tutorial-six-go.html), where it is described as inefficient. Instead, they propose using a single response queue and match request messages with response messages using correlation IDs.

## Use case: replicate.com

The serving system that backs replicate.com currently uses the existing Redis-based queue architecture.
* When a user of replicate.com makes a prediction on the website, the website's backend continuously polls Serving.
* Serving then does a non-blocking read of this particular prediction's response queue

If we move to one response queue per model (instead of one per prediction) we can either:
1. Keep the current polling mechanism from replicate.com, and create a new service in Serving that picks up responses from the response queue and saves them in a database. When the poll request comes from replicate.com, Serving reads the response from the database instead of from the response queue
2. ...or we could replace replicate.com's poll call with a webhook that goes the other direction. Like in option 1, a separate service would pick messages off the response queue, but instead of saving responses to a database, it would send them directly to replicate.com via a webhook.

---

Further reading:
* [RabbitMQ Tutorial 6: Remote procedure call (RPC)](https://www.rabbitmq.com/tutorials/tutorial-six-go.html)
* [RabbitMQ Request-Response pattern](http://mikehadlow.blogspot.com/2013/10/rabbitmq-request-response-pattern.html)

**Comment by evilstreak** [comment]
For now we're going to stick with Redis as our queueing system. I'm closing this issue because it's no longer relevant.

Some of the discussion in https://github.com/replicate/cog/issues/443 outlines an approach where we only expose an HTTP API from Cog, and make the queueing system an internal implementation detail. That seems like a good direction to go in, so we're going to make changes to the queueing API we currently use to match the HTTP API, but we aren't going to swap from Redis to AMQP.

At some point we might implement AMQP as that internal queueing system. If and when we do, we'll need to revisit this issue.
