### ISSUE TITLE
Cancel running AMQP predictions

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#442]
There is currently no way to cancel predictions that are running in the AMQP worker, other than to shut down the worker that is handling the particular prediction.

A strawman solution, in the context of Serving (the serving platform that handles prediction requests from replicate.com), could be:

* At the start of each prediction, Serving creates a prediction-specific cancellation queue
* The name of this cancellation queue is sent to the AMQP worker on the request queue
* The AMQP worker picks up the prediction job from the request queue
    * ...but before running the actual prediction it starts up a separate thread that consumes the cancellation queue
* If a message is received on the cancellation queue, it kills the running inference job
* If no cancellation message is received, the prediction completes and the cancellation queue consumer thread is killed

**Comment by evilstreak** [comment]
For now we're going to stick with Redis as our queueing system. I'm closing this issue because it's no longer relevant.

Some of the discussion in https://github.com/replicate/cog/issues/443 outlines an approach where we only expose an HTTP API from Cog, and make the queueing system an internal implementation detail. That seems like a good direction to go in, so we're going to make changes to the queueing API we currently use to match the HTTP API, but we aren't going to swap from Redis to AMQP.

Moving job cancellation into Cog rather than having it live in our serving application would still be nice, but we'll probably wait until we moving the queueing system behind an HTTP API inside Cog.
