### ISSUE TITLE
Cuda 11.7 Issue

### ISSUE THREAD

**Issue by yekta** [replicate/cog#790]
When I try to switch to Cuda 11.7 using `cuda: "11.7"` I'm getting this error:

```E: Unable to locate package python-openssl```

No idea how they are connected but my yaml works perfectly fine with `11.6.2` but throws that error with `11.7`.

Here is the repo and branch (a modified version of the official cog for Stable Diffusion): https://github.com/yekta/stable-diffusion-cog/tree/v2

**Comment by krrishdholakia** [comment]
python-openssl might be a dependency for CUDA 11.7+. Unsure on this - just a theory. 

You can install the python-openssl package using the apt package manager by running the following command in the terminal: `sudo apt-get install python-openssl`

**Comment by nickstenning** [comment]
Thanks @krrishdholakia but I'm not sure that's quite the problem here.

@yekta What version of `cog` are you using? (`cog --version` will tell you.) Please upgrade to the latest version of cog and let us know if you still see this problem as I believe it was fixed in 31872fd0a4131eef14b046fd654b969c2d4d0657 which was released in v0.5.0.
