### ISSUE TITLE
libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.

### ISSUE THREAD

**Issue by homerokzam** [replicate/cog#883]
The following error occurs:
Starting Docker image r8.im/openai/whisper@sha256:30414ee7c4fffc37e260fcab7842b5be470b9b840f2b608f5baa9bbef9a259ed and running setup()...
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
ⅹ Failed to start container: exit status 127

For the command:
cog predict r8.im/openai/whisper@sha256:30414ee7c4fffc37e260fcab7842b5be470b9b840f2b608f5baa9bbef9a259ed -i audio=/Users/homerokzam/Projects/KSpeechDir/uploads/homero.kzam@gmail.com/20221206t113238354z166100/20221206t113238354z166100.mp3

Thanks

**Comment by gonbasaldua** [comment]
@homerokzam any luck?

**Comment by homerokzam** [comment]
No. I gave up.

**Comment by arbruzaz** [comment]
Hi, I had the same issue.
I use ubuntu 20.04 LTS, cog latest version, Cuda 12, and latest version of docker desktop and it failed.
When I used docker desktop, I could not config docker daemon runtime. So, I uninstalled docker-desktop and use only docker engine instead.
make sure to use **docker engine** or if anyone knows how to config docker daemon runtime please let me know.

I fixed by followed this `https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html`
 **follow along this part**
![image](https://user-images.githubusercontent.com/54280354/224507913-a58fbaed-ec2b-4279-a011-60ea72c4ecbf.png)
![image](https://user-images.githubusercontent.com/54280354/224507940-d9e023c5-07cb-4752-bff4-f549ff2cd9aa.png)

**Comment by coolnalu** [comment]
Doesn't work on Mac, and doesn't work on Windows 10 - so I guess Linux is the only REAL supported OS? 

Which is fine but I wish I haven't wasted 2 hours trying to make it work on Windows 10 and Mac Intel/Apple Silicon.

**Comment by arbruzaz** [comment]
@coolnalu Cog doesn't support Window 10. But I have never tried on Mac because I don't have one.
But it does support on Window11. You can follow this link `https://github.com/replicate/cog/blob/main/docs/wsl2/wsl2.md`

**Comment by lucataco** [comment]
Most likely "libnvidia-ml.so.1" is not found because you dont have the nvidia-container-toolkit installed:
[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
