### ISSUE TITLE
Model HTTP interface not available until after setup

### ISSUE THREAD

**Issue by nickstenning** [replicate/cog#934]
The cog HTTP server runs the model's `setup()` in the FastAPI `startup` hook, which runs *before* the HTTP server is bound to a socket. This means that if we want to shut down the model before setup is complete, we basically can't.

(It also means that the director probably never actually sees the `Health.STARTING` state, but that's not a problem in and of itself.)

In practice this means that in production pods that receive SIGTERM before model setup has complete will hang in `Terminating` until the termination grace period expires.

We can probably solve this reasonably easily: by moving the model setup into another thread and bringing the HTTP interface up sooner.

**Comment by nickstenning** [comment]
I'll note that this issue makes nodepool draining very painful, especially if you're trying to drain a nodepool you've just created which has a bunch of brand new pods on it. Each of them gets into this state and blocks node shutdown for up to the termination grace period (~30m).

**Comment by ruravi** [comment]
@evilstreak I wrote a test to reproduce this issue here - https://github.com/replicate/cog/commit/1fbdde7d042266b9a506fafd0fd0886a095f3695 It seems the server *is* being bound even if setup is still running. It looks like the code in `@app.on_event("startup")` doesn't actually wait for `runner.setup` to complete.

Perhaps I'm missing something about how the shutdown process works. Which component issues the SIGTERM and how? If you can provide some steps to reproduce it locally, that would be helpful as well. Thanks!

**Comment by nickstenning** [comment]
Oh sorry @ruravi. This issue was addressed already by #944, which is why it looks like it works ok now.

As for shutdown, there are two different modes: 

1. standalone, in which case a SIGTERM from anything (a process supervisor, Kubernetes kubelet, etc) will shut the server down. 
2. managed lifecycle, where the server ignores SIGTERM and waits for a call to its `/shutdown` endpoint. This mode is enabled by the `--await-explicit-shutdown` option.
