### ISSUE TITLE
Error Using Cog

### ISSUE THREAD

**Issue by ElijahMansur** [replicate/cog#953]
![image](https://user-images.githubusercontent.com/76127050/223016952-a2f6dfb5-340d-499d-9636-14a11a930084.png)

This issue occurs when I try to run the command: 

![image](https://user-images.githubusercontent.com/76127050/223016985-8992c958-131a-4a35-8a8b-6c44bbe90ae6.png)

This command should make a replicate prediction for a replicate model.

**Comment by mattt** [comment]
Hi @ElijahMansur. I believe these commands are failing because Cog hasn't authenticated with Replicates image proxy. Try updating to the latest version of Cog and running `cog login`. 

If you're still seeing this problem, please reopen and share the commands you're running and the full output they produce.
