### ISSUE TITLE
Streaming output for language models

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#969]
Large language models typically stream tokens as they are running.

We've called this "progressive" output in the past in Cog, but "streaming" is the more common term, so perhaps we switch to that.

## Prior art
- [OpenAI's API](https://platform.openai.com/docs/api-reference/completions/create) returns server-side events as JSON messages in the format `{"data": "..."}` with each token.

## Proposed design

Models return an iterator of strings that are concatenated together. There is a special type called `Stream[str]` that works the same way as `Iterator[str]`, except it implies that the outputs should be concatenated together to get the final result.

For example:

```python
from cog import BasePredictor, Stream

class Predictor(BasePredictor):
    def predict() -> Stream[str]:
        yield "The "
        yield "quick "
        yield "brown "
        yield "fox "
```

The output type looks something like:

```json
{
    "type": "array",
    "items": {
        "type": "string",
    },
    "x-cog-array-type": "stream",
}
```

## Other designs considered

- We just use `Iterator[str]`. The problem with this is that the current semantics of this is in-progress snapshots of the output (e.g. diffusion models diffusing), not parts of the output that need concatenating together. You could also imagine situations where you return distinct strings as the output that you don't want concatenated together. So, we need a bit of annotation to hint that the output needs concatenating for things like Replicate's web interface.
- We return an iterator of output in the the format `["The", "The quick", "The quick brown"]`. The advantage of this is you don't have to concatenate output together to get the completed output (it's just `output[-1]`) but this returns a lot of data in each response and makes it harder to process each token as its coming in (you have to keep track of your position in the string).
- We modify Cog to output a string that can change over time. E.g. `{"output": "The"}`, `{"output": "The quick"}` etc. This means that the default case where you just want to get the complete output is really simple (no concatenation required) but it'll require some rearchitecting of Cog and makes it harder to process each token as its coming in (you have to keep track of your position in the string).
- We have a similar server-side events API to OpenAI. This is a big change.

## See also
- https://github.com/replicate/cog-llama/pull/4

**Comment by daanelson** [comment]
@bfirsh I like this. I think the one outstanding thread here is handling the case where a user generates more than 1 completion for a given prompt. OpenAI returns a stream of jsons, each of which are basically a `(completion_id, token, metadata)` tuple, where `completion_id` is between 0 and the number of requests generated. Quick example: 

```(base_ml) dans-mbp:analytics dan$ curl https://api.openai.com/v1/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "text-davinci-003",
    "prompt": "Say this is a test",
    "max_tokens": 7,
    "temperature": 0,
    "n": 3,
    "stream": true
  }'
data: {"id": "cmpl-6xmTm0BgCMDjPIYUalSbIb1ZosJro", "object": "text_completion", "created": 1679705726, "choices": [{"text": "\n", "index": 0, "logprobs": null, "finish_reason": null}], "model": "text-davinci-003"}

data: {"id": "cmpl-6xmTm0BgCMDjPIYUalSbIb1ZosJro", "object": "text_completion", "created": 1679705726, "choices": [{"text": "\n", "index": 1, "logprobs": null, "finish_reason": null}], "model": "text-davinci-003"}

data: {"id": "cmpl-6xmTm0BgCMDjPIYUalSbIb1ZosJro", "object": "text_completion", "created": 1679705726, "choices": [{"text": "\n", "index": 2, "logprobs": null, "finish_reason": null}], "model": "text-davinci-003"}

data: {"id": "cmpl-6xmTm0BgCMDjPIYUalSbIb1ZosJro", "object": "text_completion", "created": 1679705726, "choices": [{"text": "\n", "index": 0, "logprobs": null, "finish_reason": null}], "model": "text-davinci-003"}

data: {"id": "cmpl-6xmTm0BgCMDjPIYUalSbIb1ZosJro", "object": "text_completion", "created": 1679705726, "choices": [{"text": "This", "index": 0, "logprobs": null, "finish_reason": null}], "model": "text-davinci-003"}```

Interesting to note that these don't necessarily come in order, implying that the tokens aren't all being generated on the same GPU. We're not set up to do that presently, though once we have native batching under the hood, this just becomes a batch prediction instead of a single prediction where `n>1`. 

Potential approaches: 
* Return a `Stream[List[str]]`. Kind of clunky for the majority use case where we're only returning one prediction. 
* Follow OpenAI's pattern. In the instance where there are multiple sequences being generated, we return a `Stream[LLMOutput]`, where `LLMOutput` contains `index`, `text`, and potential other metadata. Great flexibility, a bit more parsing required on the downstream end. 
* Intentionally punt on this now, and add it when we get to implementing batch prediction. Either remove the `n` option for predictions, or indicate that `n>1` isn't compatible with streaming.

**Comment by bfirsh** [comment]
This is a good point, but considering we haven't figured how we want batching to work yet, I reckon we punt on this for now. The point of the `Stream` type hint is that the output can be concatenated together, and the other two designs break that.

Ref #612

**Comment by daanelson** [comment]
@bfirsh fair. I think it'd be good to have the ability to toggle streaming on & off for folks who want to return `n>1` completions for a given prompt (not how GPT-4 works but useful for some sampling applications) - or for folks who just want to get all their text all at once. 

The only way I can think of to do this in cog atm, since `predict` requires a consistent return type, is to`yield` an entire generation at once if `stream` is off. Easy enough to implement, kinda hacky. What's your take?
